#!name=剑网3推栏-屏蔽启动弹窗
#!desc=向《剑网3》推栏的启动弹窗接口返回无广告结果，不影响登录和首页内容。

hostname = m.pvp.xoyo.com

^https:\/\/m\.pvp\.xoyo\.com\/socialgw\/pop-up-window\/query-by-game(?:\?.*)?$ url script-echo-response https://raw.githubusercontent.com/sndjdndi/ios-/main/JX3-Tuilan-No-Startup-Ad-QX.js
